### PR TITLE
Added playback support, cleaned up Key variables

### PR DESCRIPTION
**Pull request by Tyzer34**
Thank you for writing this python wrapper for the SoundTouch API! I took the liberty of adding playback support, so you can start the playback of a radio station, a Spotify playlist, etc.
A small code example is provided below, to show its functionality:
```
from libsoundtouch import soundtouch_device, Source

device = soundtouch_device('192.168.0.102')

def play_from_TuneIn():
    device.init_play(Source.INTERNET_RADIO, '', '4712') # Studio Brussel

def play_from_Spotify():
    spot_user_id = "veryTopSecret"
    track_id = 'spotify:track:5J59VOgvclrhLDYUoH5OaW' # Bazart - Goud
    device.init_play(Source.SPOTIFY, spot_user_id, track_id)

def print_spot_user_id():
    # If Spotify is playing on the connected SoundTouch speaker, this will work
    print device.status().content_item.source_account

### CODE REVIEW

**Comment by Tyzer34** [comment]
The coverage check error might be due to the fact that I cleaned up the Key codes and stored them in the utils.py file. Hopefully, this doesn't form a problem.

**Comment by CharlesBlonde** [comment]
Hi @Tyzer34 and thanks for this PR and all the work you did in order to fix the build!
I'm not sure to have the time to take a look and merge it before this Weekend but it is now on my to-do list ;)

On your side, are you able squash your commits in only one in order to keep a clean history ?

Charles

**Comment by Tyzer34** [comment]
No problem! I'm happy to help out!
As far as I know, it is not possible for me to squash my commits. Normally, when you would merge the branch, you should be able to squash my commits into a single one. (and please do, because I totally agree with keeping a clean history)

**Comment by Tyzer34** [comment]
@CharlesBlonde Hi, did you find the time yet to check the code out?

**Comment by CharlesBlonde** [comment]
Hi @Tyzer34 ,

I'm currently working on it :)

I have some issues to do it working as expected but it should be merged in a few hours with an additional commit to fix everything.

Just one question: are you able to do it working with your current branch ? And which Python version are you using ? 2.7 ? 3.4 ?

Because you are sending *Key.PAUSE* for example instead of *PAUSE* in each HTTP request.

**Comment by CharlesBlonde** [comment]
I merged this PR manually and rebased all  your commits in only one (https://github.com/CharlesBlonde/libsoundtouch/commit/d566e94a2905a60ac3930510dca9817378c2aaa0)

I renamed the method *init_play* to *play_media* with *account* as an optional parameter. I hoped it will not break everything on your side.

One more time, thank you for this PR and sorry for the delay.

Charles

**Comment by CharlesBlonde** [comment]
I just created a new release (0.2.0) with your contribution.

**Pull request closed without merging**
