### PR TITLE
add Source.BLUETOOTH

### PR DESCRIPTION
**Pull request by obadz**

### CODE REVIEW

**Comment by CharlesBlonde** [comment]
Hi @obadz and thanks for this PR.

I have to fix the Travis build: it has nothing to do with your commit and I don't know why it is failing now but I have also this error on an other project.

After I'll be able to test (never used Bluetooth) and merge your PR.

**Comment by obadz** [comment]
@CharlesBlonde, thanks!

**Comment by obadz** [comment]
FYI: https://github.com/NixOS/nixpkgs/commit/caa9a1914321c61b635e47101dce9da09bacb7eb

**Comment by CharlesBlonde** [comment]
Thanks, good to know !

**Pull request merged**
